#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=GPU
#SBATCH --ntasks-per-node=1
#SBATCH --time=96:00:00
#SBATCH --gres=gpu:4
#SBATCH --mem=16G
#SBATCH --nodelist=compute-0-[17]
#SBATCH --mail-type=END,FAIL             # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=stirumal@andrew.cmu.edu     # Where to send mail

set -x
set -u
set -e
module load singularity
module load cuda-80

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0 singularity exec --nv /scratch/sashank/singularity/pytorch_sashank.sif python train.py -b 16 -lr 1